#cloud-config
packages:
  - curl
  - git
  - jq
  - gpg
  - wget
package_update: true
package_upgrade: false
runcmd:
  - bash $MY_RUNNER_DIR/pre_runner_script.sh
  - bash $MY_RUNNER_DIR/install.sh -v "$MY_RUNNER_VERSION" -d "$MY_RUNNER_DIR"
  - cd /root
  - /usr/local/bin/forgejo-runner register --no-interactive --instance "$GITHUB_SERVER_URL" --token "$MY_FORGEJO_RUNNER_REGISTRATION_TOKEN" --name "$MY_NAME" --labels "$MY_NAME:host,forgejo-runner-hetzner:host" 
  - /usr/local/bin/forgejo-runner generate-config > config.yml
  - |
    cat > /etc/systemd/system/forgejo-runner.service <<EOF
    [Unit]
    Description=Forgejo runner
    Wants=network.target
    After=network.target

    [Service]
    Type=simple
    User=runner
    Group=runner
    WorkingDirectory=/root
    ExecStart=/usr/local/bin/forgejo-runner daemon
    Restart=on-failure
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    EOF
  - systemctl start forgejo-runner.service
write_files:
  - path: $MY_RUNNER_DIR/pre_runner_script.sh
    encoding: b64
    content: $MY_PRE_RUNNER_SCRIPT_BASE64
  - path: $MY_RUNNER_DIR/install.sh
    encoding: b64
    content: $MY_INSTALL_SH_BASE64
